### ISSUE TITLE
Map route should auto update when locations are changed

### ISSUE THREAD

**Issue by drklee3** [drklee3/YOUtinerary#120]
### Expected Behavior

Get new directions data via api when event locations change, removing old route and adding new

### Current Behavior

Doesn't get new directions unless page refreshed, [`componentDidUpdate()`](https://github.com/drklee3/YOUtinerary/blob/master/packages/web/src/components/Plan.tsx#L127) in `Plan.tsx` seems to give the current state as prevstate.  Could possibly be issues with state being array and some reference comparisons. 

This also happens:

![image](https://user-images.githubusercontent.com/22536567/69918035-04065e00-1465-11ea-9cb7-7cf2acc23808.png)

* Reordering events refreshes the route with the new one.
* Changing an event location **does not** get a new route (before/after waypoints logging shows the new location for both)
* Adding a new event and adding a location **does not** get a new route.

**Comment by pbebla** [comment]
I think there should be one polyline per class, and instead of creating a new polyline when calling getDerivedStateFromProps, it should edit its path. Need to somehow initialize the polyline with path and map undefined when MapView is initialized.

**Comment by sportsman2325** [comment]
Looks like you fixed this issue.

**Comment by drklee3** [comment]
Updated description with current issue

**Comment by pbebla** [comment]
When does componentDidUpdate get called exactly?

**Comment by drklee3** [comment]
> When does componentDidUpdate get called exactly?

After `render()` when props or state is changed, possibly after children / parent rerenders too but not sure about that part.
