### ISSUE TITLE
Devs should use @google/maps instead of googleapis

### ISSUE THREAD

**Issue by drklee3** [drklee3/YOUtinerary#25]
### Expected Behavior

uses [@google/maps](https://github.com/googlemaps/google-maps-services-js) **Yarn** dep and the corresponding typedefs `@types/google__maps` (types are a dev dependency)

### Current Behavior

uses [googleapis](https://github.com/googleapis/google-api-nodejs-client) dependency which doesn't have maps support

**Comment by pbebla** [comment]
fixed via #26
